[package]
name = "examplebot"
version = "0.1.0"
authors = ["Stefan Kaufhold <cere@fastmail.fm>"]
edition = "2018"

[dependencies]
tmi-rs = { path = "../" }
env_logger = "0.6"
tokio = "0.2.0-alpha.6"
log = "0.4.8"